#pragma once

namespace ares {
  namespace packet_sets {
    /*! Packet set for intraserver communications
     */

    ARES_PACKETSET_DECLARE(server, base);
    

#define ARES_PCK_ID_NAME(ID, NAME) ARES_PACKETSET_ID_NAME(server, ID, NAME)
    // Account <-> Character
    ARES_PCK_ID_NAME(0x4001, ARES_HA_LOGIN_REQ);
    ARES_PCK_ID_NAME(0x4002, ARES_AH_LOGIN_RESULT);
    ARES_PCK_ID_NAME(0x4003, ARES_HA_PING_REQ);
    ARES_PCK_ID_NAME(0x4004, ARES_AH_PING_ACK);
    ARES_PCK_ID_NAME(0x4005, ARES_HA_ACCOUNT_AUTH_REQ);
    ARES_PCK_ID_NAME(0x4006, ARES_AH_ACCOUNT_AUTH_RESULT);
    ARES_PCK_ID_NAME(0x4007, ARES_HA_USER_COUNT);
    ARES_PCK_ID_NAME(0x4008, ARES_HA_ONLINE_ACCOUNTS);
    ARES_PCK_ID_NAME(0x4009, ARES_AH_KICK_ACCOUNT);

    // Character <-> Zone
    ARES_PCK_ID_NAME(0x4101, ARES_ZH_LOGIN_REQ);
    ARES_PCK_ID_NAME(0x4102, ARES_HZ_LOGIN_RESULT);
    ARES_PCK_ID_NAME(0x4103, ARES_ZH_PING_REQ);
    ARES_PCK_ID_NAME(0x4104, ARES_HZ_PING_ACK);
    ARES_PCK_ID_NAME(0x4105, ARES_ZH_MAP_IDS_REQ);
    ARES_PCK_ID_NAME(0x4106, ARES_HZ_MAP_IDS);
    ARES_PCK_ID_NAME(0x4107, ARES_ZH_CHAR_AUTH_REQ);
    ARES_PCK_ID_NAME(0x4108, ARES_HZ_CHAR_AUTH_RESULT);
    //    ARES_PCK_ID_NAME(0x410A, ARES_ZH_MAP_ID_LOADED);
    ARES_PCK_ID_NAME(0x410B, ARES_HZ_PRIVATE_MSG_NAME);
    ARES_PCK_ID_NAME(0x410C, ARES_ZH_GAME_RATES);
    
#undef ARES_PCK_ID_NAME
    
  }
}
