#pragma once

#include <ares/network>
#include <ares/packets>

#include "../predeclare.hpp"

namespace ares {
  namespace account {
    namespace char_server {
      ARES_DECLARE_PACKET_HANDLER_TEMPLATE();

      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_PING_REQ);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_ONLINE_AIDS);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_USER_COUNT);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_AID_AUTH_REQ);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_ACCOUNT_DATA_REQ);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_SET_AID_ONLINE);
      ARES_SIMPLE_PACKET_HANDLER(ATHENA_HA_SET_AID_OFFLINE);
      
    }
  }
}
