# ZLib
if (ARES_ZLIB_LIB)
  message ("Will link to zlib located at ${ARES_ZLIB_LIB}")
  set(ZLIB_LIBRARIES ${ARES_ZLIB_LIB})
else()
  if (WIN32)
    if (MSVC)
      message(FATAL_ERROR "Compiling on Windows with MSVC, but ARES_ZLIB_LIB is not specified. Assuming no package system is available. Specify ARES_ZLIB_LIB exlicitly (should point to zlib library")
    else()  
      find_package(ZLIB REQUIRED)  
    endif()
  else()
    find_package(ZLIB REQUIRED)  
  endif()
endif()

if (ARES_ZLIB_INCLUDE_DIRS)
  set(ZLIB_INCLUDE_DIRS ${ARES_ZLIB_INCLUDE_DIRS})
else()
  if (WIN32)
    if (MSVC)
      message(FATAL_ERROR "Compiling on Windows with MSVC, but ARES_ZLIB_INCLUDE_DIRS is not specified. Assuming no package system is available. Specify ARES_ZLIB_INCLUDE_DIRS exlicitly")
    endif()
  endif()
endif()